language: node_js
node_js: "10.15.0"
os: linux
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
  - 'npm install -g vsce'
  - 'npm install -g wtfnode'
install:
  - 'npm install --ignore-scripts'
  - 'npm install'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
  - 'vsce package'
script:
  - 'wtfnode npm test --silent'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    sonar-scanner;
    fi
deploy:
- provider: script
  script: vsce publish -p $VSCODE_TOKEN
  skip_cleanup: true
  on:
    repo: jboss-fuse/vscode-atlasmap
    branch: master
    tags: true
cache:
  directories:
    - "node_modules"
env:
  global:
    - DISPLAY=:99
    - MOZ_HEADLESS=1
addons:
  sonarcloud:
    organization: "jboss-fuse"
    branches:
      - master
  firefox: latest
